volumes:
  dev-database:
  node-cache:

services:
  helpugee-db:
    container_name: helpugee-db
    image: postgis/postgis
    restart: unless-stopped
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
    volumes:
      - dev-database:/var/lib/postgresql/data

  helpugee-db-reset:
    depends_on:
      - helpugee-db
    image: postgis/postgis
    entrypoint: "/app/reset-database.sh"
    command: "echo 'db-reset done'"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_HOST: "helpugee-db"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      RESET_DB: "${RESET_DB}"
    volumes:
      - ./database:/app

  helpugee-backend:
    build:
      args:
        APP_NAME: "backend"
      context: .
      dockerfile: ./docker/Dockerfile.dev
      target: runner
    working_dir: "/app"
    container_name: helpugee-backend
    entrypoint: /docker/entrypoint.sh
    command: "pnpm --filter backend run dev"
    environment:
      APP_NAME: "backend"
      PORT: "${HELPUGEE_BACKEND_PORT}"
      IP: "${HELPUGEE_BACKEND_HOST}"
      DB_USER: "${POSTGRES_USER}"
      DB_PASSWORD: "${POSTGRES_PASSWORD}"
      DB_HOST: "helpugee-db"
      DB_PORT: "${POSTGRES_PORT}"
      DB_NAME: "${POSTGRES_DB}"
      ACCESS_TOKEN_SECRET: "${ACCESS_TOKEN_SECRET}"
      FRONTEND_ADMIN_DEV_URL: "http://helpugee-webadmin:3000"
      FRONTEND_ADMIN_STATIC_PATH: "/app/apps/webadmin/build"
      FRONTEND_WEB_DEV_URL: "http://helpugee-webapp:3000"
      FRONTEND_WEB_STATIC_PATH: "/app/apps/webapp/build"
      NODE_ENV: "development"
    ports:
      - "0.0.0.0:${HELPUGEE_BACKEND_PORT}:${HELPUGEE_BACKEND_PORT}"
    volumes:
      - ./:/app
      - node-cache:/root/.cache

  helpugee-webadmin:
    build:
      args:
        APP_NAME: "webadmin"
      context: .
      dockerfile: ./docker/Dockerfile.dev
      target: runner
    working_dir: "/app"
    container_name: helpugee-webadmin
    entrypoint: /docker/entrypoint.sh
    command: "pnpm --filter webadmin run dev"
    environment:
      APP_NAME: "webadmin"
      VITE_PUBLIC_API_URL: "http://localhost:${HELPUGEE_BACKEND_PORT}/api/v1"
      VITE_PRIVATE_API_URL: "http://helpugee-backend:${HELPUGEE_BACKEND_PORT}/api/v1"
    ports:
      - "0.0.0.0:3334:3000"
      - "0.0.0.0:3344:3344"
    volumes:
      - ./:/app
      - node-cache:/root/.cache

  helpugee-webapp:
    build:
      args:
        APP_NAME: "webapp"
      context: .
      dockerfile: ./docker/Dockerfile.dev
      target: runner
    working_dir: "/app"
    container_name: helpugee-webapp
    entrypoint: /docker/entrypoint.sh
    command: "pnpm --filter webapp run dev"
    environment:
      APP_NAME: "webapp"
      VITE_PUBLIC_API_URL: "http://localhost:${HELPUGEE_BACKEND_PORT}/api/v1"
      VITE_PRIVATE_API_URL: "http://helpugee-backend:${HELPUGEE_BACKEND_PORT}/api/v1"
    ports:
      - "0.0.0.0:3335:3000"
      - "0.0.0.0:3345:3345"
    volumes:
      - ./:/app
      - node-cache:/root/.cache
