ARG BASE_IMAGE=node:18

FROM ${BASE_IMAGE} AS runner
RUN apt-get update && apt-get install rsync -y
RUN corepack enable
RUN corepack prepare pnpm@7.0.1 --activate
WORKDIR /app-cache
COPY .npmrc* pnpm-lock.yaml* pnpm-workspace.yaml ./
RUN --mount=type=cache,target=/root/.local/share/pnpm/store \
    pnpm fetch
COPY ./docker/entrypoint.sh /docker/

ARG APP_NAME
COPY ./apps/${APP_NAME}/package.json ./apps/${APP_NAME}/
RUN --mount=type=cache,target=/root/.local/share/pnpm/store \
    pnpm install --offline --frozen-lockfile --ignore-scripts
WORKDIR /app
COPY . ./
CMD [ "pnpm", "--filter", "${APP_NAME}", "run", "dev" ]
